import streamlit as st
from openai import OpenAI
import json
from html2image import Html2Image

# 1. SETUP API & RENDERER
client = OpenAI(api_key=st.secrets["OPENAI_API_KEY"])
hti = Html2Image(browser='chromium', custom_flags=['--no-sandbox', '--disable-dev-shm-usage', '--headless', '--disable-gpu'])

# 2. FUNGSI AI (Hanya satu kali panggil untuk semua data)
def get_recipe_data(judul, bahan, langkah, trik):
    prompt = f"""
    Rapikan resep ini ke JSON profesional.
    Judul: {judul}, Bahan: {bahan}, Langkah: {langkah}, Trik: {trik}
    Output JSON:
    {{
        "judul": "...",
        "deskripsi": "...",
        "bahan": ["..."],
        "langkah": ["..."],
        "trik": "...",
        "kalori": "...",
        "image_prompt": "Professional food photography of {judul}, minimalist"
    }}
    """
    res = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        response_format={ "type": "json_object" }
    )
    return json.loads(res.choices[0].message.content)

# 3. UI UTAMA
st.set_page_config(page_title="ChefArt AI", layout="centered")

st.title("👨‍🍳 Generator Poster Resep")
st.write("Isi detail di bawah, AI akan merapikan dan mendesainnya.")

# Input Form
with st.container():
    in_judul = st.text_input("Nama Masakan", "Telur Dadar Crispy")
    col1, col2 = st.columns(2)
    with col1:
        in_bahan = st.text_area("Bahan-bahan", "2 telur, garam, daun bawang", height=100)
    with col2:
        in_langkah = st.text_area("Cara Masak", "Kocok telur, goreng kering", height=100)
    in_trik = st.text_input("Trik Rahasia", "Gunakan minyak sangat panas")
    
    use_image = st.checkbox("Gunakan AI Image (DALL-E 3)", value=True)

if st.button("🪄 BUAT POSTER SEKARANG", use_container_width=True):
    if not in_judul or not in_bahan:
        st.warning("Mohon isi judul dan bahan.")
    else:
        with st.spinner("Sedang memproses..."):
            try:
                # STEP 1: Dapatkan Data dari AI
                data = get_recipe_data(in_judul, in_bahan, in_langkah, in_trik)
                
                # STEP 2: Generate Gambar (Opsional)
                img_url = "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=1000"
                if use_image:
                    img_res = client.images.generate(model="dall-e-3", prompt=data['image_prompt'], n=1)
                    img_url = img_res.data[0].url

                # STEP 3: Template HTML Modern
                html_poster = f"""
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
                <div id="poster" style="width: 500px; background: #f9fafb; font-family: 'Inter', sans-serif; color: #1f2937; padding: 20px; border: 1px solid #e5e7eb;">
                    <div style="width: 100%; height: 250px; background: url('{img_url}') center/cover; border-radius: 12px; margin-bottom: 20px;"></div>
                    
                    <h1 style="margin: 0 0 10px 0; font-size: 28px; color: #111827;">{data['judul']}</h1>
                    <p style="margin: 0 0 20px 0; font-size: 14px; color: #6b7280; font-style: italic;">{data['deskripsi']}</p>
                    
                    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px;">
                        <div style="background: white; padding: 15px; border-radius: 10px; border: 1px solid #f3f4f6;">
                            <b style="color: #ef4444; font-size: 12px;">BAHAN</b>
                            <ul style="padding-left: 15px; font-size: 12px; margin-top: 10px;">
                                {"".join([f"<li>{b}</li>" for b in data['bahan']])}
                            </ul>
                        </div>
                        <div style="background: white; padding: 15px; border-radius: 10px; border: 1px solid #f3f4f6;">
                            <b style="color: #3b82f6; font-size: 12px;">LANGKAH</b>
                            <div style="font-size: 11px; margin-top: 10px; line-height: 1.5;">
                                {" ".join([f"<b>{i+1}.</b> {l}<br>" for i, l in enumerate(data['langkah'])])}
                            </div>
                        </div>
                    </div>
                    
                    <div style="background: #eff6ff; padding: 15px; border-radius: 10px; border-left: 4px solid #3b82f6;">
                        <span style="font-size: 12px; font-weight: bold; color: #1e40af;">💡 TRIK: {data['trik']}</span>
                    </div>
                    
                    <div style="margin-top: 15px; text-align: center; font-size: 10px; color: #9ca3af;">
                        ESTIMASI: {data['kalori']} KCAL | GENERATED BY CHEFART AI
                    </div>
                </div>
                """

                # TAMPILKAN PREVIEW DULU (Agar tidak blank)
                st.subheader("Preview Poster")
                st.components.v1.html(html_poster, height=750)

                # STEP 4: Proses Screenshot Gambar (Di latar belakang)
                st.write("Sedang menyiapkan file download...")
                hti.screenshot(html_str=html_poster, save_as='result.png')
                
                with open("result.png", "rb") as f:
                    st.download_button("📥 DOWNLOAD POSTER (PNG)", f, "resep_chefart.png", "image/png")

            except Exception as e:
                st.error(f"Terjadi kesalahan: {e}")
